apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://115.79.204.120:6443
  name: k8s-local
contexts:
- context:
    cluster: k8s-local
    namespace: default
    user: lamtt-k8s-local
  name: lamtt-k8s-local
current-context: lamtt-k8s-local
kind: Config
users:
- name: lamtt-k8s-local
  user:
    token: REDACTED
