apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://k8s.younetmedia.com
  name: k8s-ovh
contexts:
- context:
    cluster: k8s-ovh
    user: lamtt-k8s-ovh
  name: lamtt-k8s-ovh
current-context: lamtt-k8s-ovh
kind: Config
users:
- name: lamtt-k8s-ovh
  user:
    token: REDACTED
