export const jobLevelMapper = {
  singer: '0',
  songwriter: '0',
  gv: '97',
  cook: '0',
  dancer: '0',
  'hieu truong': '99',
  choreographer: '0',
  teacher: '0',
  actor: '0',
  hlv: '0',
  'fashion stylist': '97',
  editor: '97',
  'head coach': '0',
  'thieu uy': '97',
  photographer: '97',
  'digital filmmaker': '97',
  freelancer: '97',
  defender: '0',
  'y ta': '97',
  chef: '0',
  'bao mau': '0',
  lecturer: '97',
  pharmacist: '0',
  farmer: '0',
  waiter: '97',
  airman: '97',
  composer: '0',
  architect: '97',
  waitress: '97',
  translator: '97',
  'free-lancer': '0',
  soldier: '0',
  copywriter: '97',
  'tien dao': '0',
  'thuyen truong': '0',
  'giao vien': '97',
  'dieu duong': '0',
  'duoc si': '0',
  'duoc sy': '0',
  'cau thu': '0',
  'bien tap vien': '97',
  'huan luyen vien': '97',
  'si quan': '97',
  'sy quan': '97',
  'ca si': '0',
  'ca sy': '0',
  'dien vien': '0',
  'gia su': '0',
  'bi thu': '94',
  'hieu pho': '99',
  nurse: '97',
  'thay giao': '97',
  doctor: '97',
  'phong van vien': '97',
  'giao dich vien': '0',
  vdv: '0',
  'van dong vien': '0',
  student: '94',
  'hoc vien': '94',
  'lop truong': '94',
  'sinh vien': '94',
  'doan vien': '94',
  'hoc sinh': '94',
  ctv: '95',
  collaborator: '97',
  internship: '95',
  trainee: '95',
  'cong tac vien': '95',
  'thuc tap': '95',
  admin: '98',
  technician: '97',
  'ke toan': '97',
  marketing: '97',
  'nhan vien': '97',
  'cong nhan': '97',
  hr: '97',
  'chuyen vien': '97',
  'public relations': '97',
  administrator: '97',
  'quan tri vien': '97',
  engineer: '97',
  coder: '97',
  design: '97',
  support: '97',
  'phu trach kinh doanh': '97',
  'ky thuat vien': '97',
  'ki thuat vien': '97',
  'lap trinh vien': '97',
  'ky su': '97',
  'ki su': '97',
  sales: '97',
  sale: '97',
  designer: '97',
  programmer: '97',
  developer: '97',
  it: '97',
  btv: '97',
  'huong dan vien': '97',
  'thu ky': '97',
  'thu ki': '97',
  'tro ly': '97',
  'tro li': '97',
  executive: '97',
  producer: '97',
  staff: '97',
  adminstrator: '97',
  deverloper: '97',
  analyst: '97',
  'kien truc su': '97',
  lawyer: '97',
  adm: '97',
  cashier: '97',
  assistant: '97',
  bartender: '97',
  'co van': '97',
  member: '97',
  researcher: '97',
  accountant: '97',
  tester: '97',
  'may pho': '97',
  'may truong': '97',
  consultant: '97',
  secretary: '97',
  'dieu duong vien': '97',
  seller: '97',
  receptionist: '97',
  'quan sat vien': '97',
  'human resource': '97',
  coordinator: '98',
  auditor: '97',
  counselor: '97',
  addmin: '97',
  nv: '97',
  'cong to vien': '97',
  'bac si': '97',
  'thu quy': '97',
  'thu ngan': '97',
  'phuc vu': '97',
  'tu van vien': '97',
  'nha bao': '97',
  'tap vu': '97',
  'kiem toan': '97',
  'bao ve': '97',
  'le tan': '97',
  'giu xe': '97',
  'kinh doanh': '97',
  'giam sat': '98',
  manager: '98',
  management: '98',
  leader: '98',
  'truong phong': '98',
  'quan li': '98',
  'quan ly': '98',
  supervisor: '98',
  head: '98',
  senior: '98',
  'truong ban': '98',
  supervisior: '98',
  'truong nhom': '98',
  'technical lead': '98',
  chief: '99',
  ceo: '99',
  founder: '99',
  chairman: '99',
  president: '99',
  director: '99',
  'giam doc': '99',
  'chu tich': '99',
  'c.e.o': '99',
  gd: '99',
  'chu nhiem': '99',
  'bo truong': '99',
  'pho tong': '99',
  boss: '99',
  tgd: '99',
  'co-founder': '99',
  'cuc truong': '99',
};