const xlsx = require('xlsx');

const data = [
  [
    "]",
    "TEST CASE ID\t",
    "MODULE/FEATURE\t",
    "TEST NAME",
    "PRE-CONDITION        ",
    "TEST STEPS\t",
    "TEST DATA\t",
    "EXPECTED RESULT",
    "ACTUAL RESULT",
    "STATUS",
    "PRIORITY",
    "TEST TYPE",
    "ASSIGNED TO",
    "BUG ID",
    "BUG STATUS",
    "REMARKS"
  ],
  [
    "",
    "TC-ECI Sync-001",
    "",
    "[High] [Positive] Field lock_sync tồn tại đúng cấu trúc trên bảng industries",
    "Bảng industries đã được apply script update database mới nhất.",
    "1. Query kiểm tra cấu trúc bảng industries.\n2. Kiểm tra field lock_sync.",
    "(Không có)",
    "Field lock_sync tồn tại, kiểu BOOLEAN, có default value = FALSE (0).",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-002",
    "",
    "[High] [Positive] Giá trị mặc định của lock_sync khi thêm mới industry",
    "Bảng industries đã có field lock_sync.",
    "1. Thực hiện Insert một industry mới vào DB.\n2. Query lại record vừa tạo để kiểm tra field lock_sync.",
    "Insert industry mới (VD: ID 999)",
    "lock_sync của record mới có giá trị = FALSE (0) (Không bị lock theo mặc định).",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-003",
    "",
    "[High] [Positive] Toggle lock_sync: bật/tắt thành công",
    "Bảng industries có sẵn industry A.",
    "1. Update lock_sync = TRUE cho industry A, query kiểm tra.\n2. Update lock_sync = FALSE cho industry A, query kiểm tra.",
    "Industry A",
    "Bước 1 lưu thành công giá trị 1. \nBước 2 lưu thành công giá trị 0.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-004",
    "",
    "[High] [Positive] Sync bình thường: industry KHÔNG bị lock",
    "Có sẵn dữ liệu PIW/PIM trong period [T1 → T2] cần sync.",
    "1. Đảm bảo Industry 101 có lock_sync = FALSE.\n2. Chạy luồng sync.\n3. Kiểm tra DB sau khi sync.",
    "list_industry = [101], period = [T1, T2]",
    "Các records PIW/PIM thuộc industry 101 được update thành công theo dữ liệu PI mới nhất.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-005",
    "",
    "[High] [Negative] Skip đúng industry bị lock",
    "Có sẵn dữ liệu PIW/PIM trong period [T1 → T2].",
    "1. Đảm bảo Industry 102 có lock_sync = TRUE.\n2. Chạy luồng sync.\n3. Kiểm tra và đối chiếu GMV/Sold trước và sau sync.",
    "list_industry = [102], period = [T1, T2]",
    "Records PIW/PIM thuộc industry 102 KHÔNG được update. Dữ liệu giữ nguyên giá trị cũ.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-006",
    "",
    "[High] [Positive] Mixed: Request có cả locked và non-locked industry",
    "Có dữ liệu PIW/PIM cho các Industry 101, 102, 103.",
    "1. Set DB: 101 (FALSE), 102 (TRUE), 103 (FALSE).\n2. Chạy luồng sync cho cả 3 industry cùng lúc.\n3. Kiểm tra DB sau sync.",
    "list_industry = [101, 102, 103]",
    "- Industry 101, 103: Records được update bình thường.\n- Industry 102: Records bị SKIP, data giữ nguyên.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-007",
    "",
    "[Medium] [Edge] PI không có industry_id (NULL) -> Vẫn sync bình thường",
    "Có Product Item X có industry_id = NULL trong PIW/PIM.",
    "1. Set DB có 1 list industry bị lock bất kỳ.\n2. Chạy luồng sync.\n3. Kiểm tra data của PI X.",
    "industry_id = NULL",
    "Record của PI X được update bình thường, không bị ảnh hưởng bởi logic lock.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-008",
    "",
    "[Medium] [Negative] Toàn bộ industry trong request đều bị lock",
    "Có dữ liệu PIW/PIM cho 101 và 102.",
    "1. Set DB: 101 và 102 đều có lock_sync = TRUE.\n2. Chạy luồng sync.\n3. Kiểm tra DB.",
    "list_industry = [101, 102]",
    "Kịch bản sync kết thúc, 0 records được update. Dữ liệu trên WS/MS không có bất kỳ thay đổi nào.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-009",
    "",
    "[High] [Positive] Sync chiều 1 (PI → PIW/PIM), kiểm tra lock tại WS/MS",
    "Industry 102 có lock_sync = TRUE, có record trên PIW/PIM.",
    "1. Kích hoạt chạy sync chiều 1 (PI → PIW/PIM).\n2. Kiểm tra log và database.",
    "Sync chiều 1, Industry 102",
    "Script kiểm tra cờ lock_sync tại bảng industry trước khi update và thực hiện SKIP thành công.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-010",
    "",
    "[High] [Positive] Sync chiều 2 (PIW/PIM → Lookup PI), kiểm tra lock tại PI",
    "PI của industry 102 có lock_sync = TRUE.",
    "1. Kích hoạt chạy sync chiều 2 (PIW/PIM → Lookup PI).\n2. Kiểm tra log và database.",
    "Sync chiều 2, Industry 102",
    "Nếu PI tương ứng thuộc industry đang bị lock -> Script thực hiện SKIP, không lookup/update.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-011",
    "",
    "[High] [Positive] Unlock industry -> sync bình thường từ lần kế tiếp",
    "Industry 102 ĐANG có lock_sync = TRUE.",
    "1. Update DB: Set lock_sync = FALSE cho 102.\n2. Chạy lại luồng sync ngay sau đó.\n3. Kiểm tra DB.",
    "list_industry = [102]",
    "Industry 102 được hệ thống ghi nhận đã unlock và tiến hành update records bình thường.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-012",
    "",
    "[High] [Positive] Lock thêm industry mới -> áp dụng ngay lần sync kế tiếp",
    "Industry 105 ĐANG có lock_sync = FALSE.",
    "1. Update DB: Set lock_sync = TRUE cho 105.\n2. Chạy lại luồng sync ngay sau đó.\n3. Kiểm tra DB.",
    "list_industry = [105]",
    "Industry 105 được hệ thống ghi nhận đã lock và tiến hành SKIP các records của industry này.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-013",
    "",
    "[Medium] [Positive] Thay đổi lock list đầy đủ: gỡ lock cũ + thêm lock mới",
    "DB: 102 (TRUE), 101 & 105 (FALSE).",
    "1. Update DB: Đổi 102 thành FALSE, 105 thành TRUE.\n2. Chạy sync cho list [101, 102, 105].\n3. Kiểm tra DB.",
    "list_industry = [101, 102, 105]",
    "- Industry 101, 102: Được sync bình thường.\n- Industry 105: Bị SKIP.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-014",
    "",
    "[Medium] [Edge] Thay đổi lock phải thực hiện trước khi sync",
    "Industry 102 đang có lock_sync = TRUE.",
    "1. Chuẩn bị request sync nhưng chưa chạy.\n2. Unlock 102 trên DB.\n3. Kích hoạt chạy script sync.\n4. Kiểm tra DB.",
    "list_industry = [102]",
    "Script đọc trạng thái lock_sync = FALSE tại thời điểm chạy và tiến hành sync bình thường cho 102.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-015",
    "",
    "[High] [Positive] Report Sync: Sync Mode = \"All Field\" -> áp dụng lock",
    "Industry 102 có lock_sync = TRUE.",
    "1. Chạy Report Sync với cấu hình Mode = \"All Field\".\n2. Kiểm tra log và database.",
    "Mode: All Field, Industry 102",
    "Industry 102 bị SKIP trong quá trình Report Sync.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-016",
    "",
    "[Medium] [Negative] Report Sync: Sync Mode = \"Only Label\" -> KHÔNG áp dụng lock",
    "Industry 102 có lock_sync = TRUE.",
    "1. Chạy Report Sync với cấu hình Mode = \"Only Label\".\n2. Kiểm tra DB.",
    "Mode: Only Label, Industry 102",
    "Records của industry 102 vẫn được sync bình thường (Logic lock không có tác dụng ở mode này).",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-017",
    "",
    "[Low] [Positive] Setup new industry: industry mới không bị block",
    "Có sẵn lock list hiện tại = [101, 102].",
    "1. Chạy script setup new industry cho industry C (mới, default FALSE).\n2. Kiểm tra tiến trình setup.",
    "Setup Industry C",
    "Industry C được setup thành công, không bị block bởi lock list hiện hành.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-018",
    "",
    "[Low] [Negative] Setup new industry có lock_sync = TRUE -> bị SKIP",
    "Industry D mới được thêm vào với cờ lock_sync = TRUE ngay từ đầu.",
    "1. Chạy script setup new industry cho industry D.\n2. Kiểm tra log setup.",
    "Setup Industry D",
    "Industry D bị SKIP trong quá trình setup sync.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-019",
    "",
    "[Low] [Positive] Tính nhất quán: cùng điều kiện -> cùng kết quả",
    "Cấu hình DB và parameter không đổi.",
    "1. Chạy script sync lần 1.\n2. Chạy script sync lần 2 với y hệt điều kiện.\n3. So sánh kết quả.",
    "list_industry = [101, 102]",
    "Kết quả sync (số record updated/skipped) hoàn toàn giống nhau ở cả 2 lần chạy.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-020",
    "",
    "[Low] [Positive] Tính linh hoạt: không cần thay đổi code để update lock list",
    "Đang có code sync trên production/staging.",
    "1. Update lock_sync trực tiếp trên DB.\n2. Chạy sync ngay lập tức mà không restart service hay deploy lại code.",
    "(Thay đổi DB động)",
    "Script tự động đọc DB và áp dụng đúng trạng thái lock mới nhất.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-021",
    "",
    "[Medium] [Positive] Luồng sync cũ không bị ảnh hưởng khi lock list rỗng (Regression)",
    "Đảm bảo DB tất cả industry đều có lock_sync = FALSE.",
    "1. Chạy luồng sync full toàn bộ data như cũ.\n2. Đối chiếu performance và kết quả data.",
    "Sync full không lock",
    "Tất cả records được update bình thường giống hệt behavior trước khi release tính năng này (Không xảy ra regression).",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ],
  [
    "",
    "TC-ECI Sync-022",
    "",
    "[Medium] [Positive] Non-locked industry sync không bị ảnh hưởng về performance",
    "DB có số lượng lớn industry, chỉ vài industry bị lock.",
    "1. Chạy luồng sync.\n2. Theo dõi thời gian xử lý (Execution time) của script.",
    "Sync full có mix lock",
    "Các industry không bị lock vẫn sync mượt mà. Thời gian xử lý không bị chậm hơn đáng kể so với bản cũ.",
    "",
    "",
    "High",
    "Functional",
    "LAMTT"
  ]
];

const wb = xlsx.utils.book_new();
const ws = xlsx.utils.aoa_to_sheet(data);

// Define columns width for better readability
const wscols = [
  {wch: 5},
  {wch: 15},
  {wch: 20},
  {wch: 60},
  {wch: 50},
  {wch: 60},
  {wch: 40},
  {wch: 60},
  {wch: 15},
  {wch: 10},
  {wch: 10},
  {wch: 15},
  {wch: 15},
  {wch: 15},
  {wch: 15},
  {wch: 20}
];
ws['!cols'] = wscols;

xlsx.utils.book_append_sheet(wb, ws, "ECI Lock Industry Sync");

// Write to file
xlsx.writeFile(wb, 'TestCases_LockIndustrySync.xlsx');
console.log('Successfully created TestCases_LockIndustrySync.xlsx');
